METRIC_REGISTRY = {
    "Accuracy": {},
    "Precision": {},
    "Recall": {},
    "F1Score": {},
    "AUROC": {},
    "ConfusionMatrix": {},
    "MeanAbsoluteError": {},
    "MeanSquaredError": {},
    "MeanSquaredLogError": {},
    "R2Score": {},
    "JaccardIndex": {"task": "binary"},
    "Dice": {"average": "macro"},
    "RetrievalMRR": {},
    "RetrievalNormalizedDCG": {},
    "CosineSimilarity": {},
    "ExplainedVariance": {},
    "SpearmanCorrcoef": {},
}
